# since the image size is 550Mb, we need to move to multi-stage builds

# Build stage
FROM golang:1.22-alpine3.19 AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go    
 
# Run stage 
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/main . 
COPY app.env .

EXPOSE 8080
ENTRYPOINT ["/app/main"]
