version: "1.0"
services:
  redis:
    image: redis:7-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=changeme
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - "6379:6379"

volumes:
  data-volume: