version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=changeme
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - password-manager-network
    ports:
      - "6380:6379"
  
  api:
    build: .
    image: api:1.0
    restart: always
    environment:
      - ENVIROMENT=testing
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - REDIS_PASSWORD=changeme
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command: [ "/app/main" ]
    networks:
      - password-manager-network

networks:
  password-manager-network:
    driver: bridge
    
volumes:
  data-volume: